"""
report.py — 12节标准报告生成器
功能: 将各分析模块的结果组装为标准化Markdown报告
支持双语(英文/中文)输出
"""

import json
from datetime import datetime


# ═══ Bilingual Translation Dictionary ═══
TRANSLATIONS = {
    "en": {
        "深度分析报告": "Deep Analysis Report",
        "分析时间": "Analysis Time",
        "分析工具": "Analysis Tool",
        "文件路径": "File Path",
        "一、结构概览": "1. Structure Overview",
        "二、架构分析": "2. Architecture Analysis",
        "三、复杂度分析": "3. Complexity Analysis",
        "四、调用图分析": "4. Call Graph Analysis",
        "五、影响面分析": "5. Impact Analysis",
        "六、死代码检测": "6. Dead Code Detection",
        "七、依赖分析": "7. Dependency Analysis",
        "八、代码意图": "8. Code Intent (Agent Layer)",
        "九、文档覆盖率": "9. Documentation Coverage",
        "十、重构建议": "10. Refactoring Suggestions",
        "十一、综合评估": "11. Quality Assessment",
        "十二、总结": "12. Summary",
        "总行数": "Total Lines",
        "有效代码行(SLOC)": "Source Lines of Code (SLOC)",
        "类数量": "Classes",
        "函数数量": "Functions",
        "方法数量": "Methods",
        "导入数量": "Imports",
        "参数总数": "Total Arguments",
        "包含空行": "including blank lines",
        "有效语句": "executable statements",
        "模块级": "module-level",
        "含继承方法": "including inherited",
        "复杂度分布": "Complexity Distribution",
        "圈复杂度": "Cyclomatic Complexity",
        "认知复杂度": "Cognitive Complexity",
        "整体评级": "Overall Rating",
        "平均": "Avg",
        "最大": "Max",
        "调用边": "Call Edges",
        "用户定义函数": "User-defined Functions",
        "被调用函数": "Called Functions",
        "最大调用深度": "Max Call Depth",
        "调用关系": "Call Relationships",
        "调用者": "Caller",
        "被调用者": "Callee",
        "入口点": "Entry Points",
        "修改目标": "Modification Target",
        "直接影响": "Direct Impact",
        "间接影响": "Indirect Impact",
        "总影响": "Total Impact",
        "无调用关系，影响面分析不适用": "No call relationships found. Impact analysis not applicable.",
        "覆盖率": "Coverage",
        "未覆盖函数": "Unreachable Functions",
        "风险": "Risk",
        "无调用路径": "No call path",
        "所有用户定义函数均有调用路径": "All user-defined functions have call paths",
        "特殊方法": "special methods",
        "循环导入": "Circular Imports",
        "依赖类型": "Dependency Type",
        "数量": "Count",
        "模块列表": "Modules",
        "stdlib": "stdlib",
        "third-party": "third-party",
        "local": "local",
        "此部分由Agent层(LLM)分析生成": "This section requires LLM-based Agent layer analysis",
        "code_analyzer工具仅提供静态数据": "code_analyzer provides static data only",
        "总函数/方法": "Total Functions/Methods",
        "有docstring": "With Docstring",
        "缺失docstring的方法": "Methods Missing Docstring",
        "位置": "Location",
        "优先级": "Priority",
        "重构建议": "Refactoring Suggestions",
        "建议立即修复": "Fix Immediately",
        "建议后续优化": "Optimize Later",
        "未发现需要重构的问题": "No refactoring issues found",
        "综合评估": "Quality Assessment",
        "维度": "Dimension",
        "得分": "Score",
        "权重": "Weight",
        "说明": "Description",
        "复杂度": "Complexity",
        "文档": "Documentation",
        "结构": "Structure",
        "死代码": "Dead Code",
        "依赖": "Dependencies",
        "综合": "Overall",
        "优势": "Strengths",
        "问题": "Issues",
        "整体评价": "Overall Assessment",
        "继承": "Inherits",
        "无": "None",
        "基础类": "Base class",
        "设计模式推断": "Design Pattern Inference",
        "含类方法（可能的工厂/注册模式）": "Has class methods (possible factory/registry pattern)",
        "含静态方法（工具类）": "Has static methods (utility class)",
        "未检测到明显的设计模式": "No obvious design patterns detected",
        "仅显示前": "Showing first",
        "共": "of total",
        "需重构依赖方向": "Refactor dependency direction",
        "复杂度但无docstring": "complexity but no docstring",
        "建议拆分": "Consider splitting",
        "可考虑简化": "Consider simplifying",
        "无调用路径，可考虑移除或添加入口": "No call path, consider removing or adding entry point",
        "本报告由code_analyzer工具自动生成": "This report was auto-generated by code_analyzer",
        "Agent层分析由LLM完成": "Agent layer analysis powered by LLM",
        "分析报告生成时间": "Report generated at",
        "指标": "Metric",
        "数值": "Value",
        "类结构": "Class Structure",
        "方法": "Methods",
        "函数": "Function",
        "建议": "Suggestion",
        "类/方法": "Class/Method",
        "行数": "Lines",
        "评级": "Rating",
        "行号": "Line",
        "文档覆盖率": "Documentation Coverage",
        "循环依赖详情": "Circular Dependency Details",
        "立即修复": "Fix Immediately",
        "后续优化": "Optimize Later",
        "优势": "Strengths",
        "问题": "Issues",
        "无明显问题": "No obvious issues",
        "无明显优势": "No obvious strengths",
    },
    "zh": {
        "深度分析报告": "深度分析报告",
        "分析时间": "分析时间",
        "分析工具": "分析工具",
        "文件路径": "文件路径",
        "一、结构概览": "一、结构概览",
        "二、架构分析": "二、架构分析",
        "三、复杂度分析": "三、复杂度分析",
        "四、调用图分析": "四、调用图分析",
        "五、影响面分析": "五、影响面分析",
        "六、死代码检测": "六、死代码检测",
        "七、依赖分析": "七、依赖分析",
        "八、代码意图": "八、代码意图",
        "九、文档覆盖率": "九、文档覆盖率",
        "十、重构建议": "十、重构建议",
        "十一、综合评估": "十一、综合评估",
        "十二、总结": "十二、总结",
        "总行数": "总行数",
        "有效代码行(SLOC)": "有效代码行(SLOC)",
        "类数量": "类数量",
        "函数数量": "函数数量",
        "方法数量": "方法数量",
        "导入数量": "导入数量",
        "参数总数": "参数总数",
        "包含空行": "包含空行",
        "有效语句": "有效语句",
        "模块级": "模块级",
        "含继承方法": "含继承方法",
        "复杂度分布": "复杂度分布",
        "圈复杂度": "圈复杂度",
        "认知复杂度": "认知复杂度",
        "整体评级": "整体评级",
        "平均": "平均",
        "最大": "最大",
        "调用边": "调用边",
        "用户定义函数": "用户定义函数",
        "被调用函数": "被调用函数",
        "最大调用深度": "最大调用深度",
        "调用关系": "调用关系",
        "调用者": "调用者",
        "被调用者": "被调用者",
        "入口点": "入口点",
        "修改目标": "修改目标",
        "直接影响": "直接影响",
        "间接影响": "间接影响",
        "总影响": "总影响",
        "无调用关系，影响面分析不适用": "无调用关系，影响面分析不适用",
        "覆盖率": "覆盖率",
        "未覆盖函数": "未覆盖函数",
        "风险": "风险",
        "无调用路径": "无调用路径",
        "所有用户定义函数均有调用路径": "所有用户定义函数均有调用路径",
        "特殊方法": "特殊方法",
        "循环导入": "循环导入",
        "依赖类型": "依赖类型",
        "数量": "数量",
        "模块列表": "模块列表",
        "stdlib": "stdlib",
        "third-party": "third-party",
        "local": "local",
        "此部分由Agent层(LLM)分析生成": "此部分由Agent层(LLM)分析生成",
        "code_analyzer工具仅提供静态数据": "code_analyzer工具仅提供静态数据",
        "总函数/方法": "总函数/方法",
        "有docstring": "有docstring",
        "缺失docstring的方法": "缺失docstring的方法",
        "位置": "位置",
        "优先级": "优先级",
        "重构建议": "重构建议",
        "建议立即修复": "建议立即修复",
        "建议后续优化": "建议后续优化",
        "未发现需要重构的问题": "未发现需要重构的问题",
        "综合评估": "综合评估",
        "维度": "维度",
        "得分": "得分",
        "权重": "权重",
        "说明": "说明",
        "复杂度": "复杂度",
        "文档": "文档",
        "结构": "结构",
        "死代码": "死代码",
        "依赖": "依赖",
        "综合": "综合",
        "优势": "优势",
        "问题": "问题",
        "整体评价": "整体评价",
        "继承": "继承",
        "无": "无",
        "基础类": "基础类",
        "设计模式推断": "设计模式推断",
        "含类方法（可能的工厂/注册模式）": "含类方法（可能的工厂/注册模式）",
        "含静态方法（工具类）": "含静态方法（工具类）",
        "未检测到明显的设计模式": "未检测到明显的设计模式",
        "仅显示前": "仅显示前",
        "共": "共",
        "需重构依赖方向": "需重构依赖方向",
        "复杂度但无docstring": "复杂度但无docstring",
        "建议拆分": "建议拆分",
        "可考虑简化": "可考虑简化",
        "无调用路径，可考虑移除或添加入口": "无调用路径，可考虑移除或添加入口",
        "本报告由code_analyzer工具自动生成": "本报告由code_analyzer工具自动生成",
        "Agent层分析由LLM完成": "Agent层分析由LLM完成",
        "分析报告生成时间": "分析报告生成时间",
        "指标": "指标",
        "数值": "数值",
        "类结构": "类结构",
        "方法": "方法",
        "函数": "函数",
        "建议": "建议",
        "类/方法": "类/方法",
        "行数": "行数",
        "评级": "评级",
        "行号": "行号",
        "文档覆盖率": "文档覆盖率",
        "循环依赖详情": "循环依赖详情",
        "立即修复": "立即修复",
        "后续优化": "后续优化",
        "优势": "优势",
        "问题": "问题",
        "无明显问题": "无明显问题",
        "无明显优势": "无明显优势",
    },
}


def _t(key: str, lang: str = "en") -> str:
    """Look up a translation key. Returns the key itself if not found."""
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)


# 复杂度等级映射
def _complexity_grade(cc: int) -> str:
    if cc <= 5:
        return "A"
    elif cc <= 10:
        return "B"
    elif cc <= 20:
        return "C"
    elif cc <= 50:
        return "D"
    else:
        return "F"


def _grade_color(grade: str) -> str:
    return {"A": "✅", "B": "✅", "C": "⚠️", "D": "🔴", "F": "💀"}.get(grade, "❓")


def generate_report(
    structure,
    call_graph,
    impact_analysis,
    dead_code_result,
    dependency_result,
    ai_analysis: dict = None,
    lang: str = "en",
) -> str:
    """
    生成12节标准报告

    Args:
        structure: StructureAnalysis
        call_graph: CallGraph
        impact_analysis: ImpactAnalysis
        dead_code_result: DeadCodeResult
        dependency_result: DependencyInfo
        ai_analysis: Agent层分析结果（可选）
        lang: Report language ('en' or 'zh'), default 'en'
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    filename = structure.file_path

    sections = []

    # ═══ 一、结构概览 ═══
    sections.append(_section_1(structure, lang))

    # ═══ 二、架构分析 ═══
    sections.append(_section_2(structure, lang))

    # ═══ 三、复杂度分析 ═══
    sections.append(_section_3(structure, lang))

    # ═══ 四、调用图分析 ═══
    sections.append(_section_4(call_graph, lang))

    # ═══ 五、影响面分析 ═══
    sections.append(_section_5(impact_analysis, lang))

    # ═══ 六、死代码检测 ═══
    sections.append(_section_6(dead_code_result, lang))

    # ═══ 七、依赖分析 ═══
    sections.append(_section_7(dependency_result, lang))

    # ═══ 八、代码意图（Agent层） ═══
    sections.append(_section_8(ai_analysis, lang))

    # ═══ 九、文档覆盖率 ═══
    sections.append(_section_9(structure, lang))

    # ═══ 十、重构建议 ═══
    sections.append(_section_10(structure, call_graph, dead_code_result, dependency_result, lang))

    # ═══ 十一、综合评估 ═══
    sections.append(_section_11(structure, call_graph, dead_code_result, dependency_result, lang))

    # ═══ 十二、总结 ═══
    sections.append(_section_12(structure, call_graph, dead_code_result, lang))

    # 组装报告
    header = f"""# {filename} {_t('深度分析报告', lang)}

**{_t('分析时间', lang)}**: {now}
**{_t('分析工具', lang)}**: python-code-analyst v2.0.0
**{_t('文件路径', lang)}**: `{filename}`

---"""

    footer = f"""
---

*{_t('分析报告生成时间', lang)}: {now}*
*{_t('分析工具', lang)}: python-code-analyst v2.0.0*
*⚠️ {_t('本报告由code_analyzer工具自动生成', lang)}，{_t('Agent层分析由LLM完成', lang)}*"""

    return header + "\n\n".join(sections) + footer


def _section_1(structure, lang="en") -> str:
    """一、结构概览"""
    # 计算综合评分
    grades = []
    for f in structure.all_functions:
        g = _complexity_grade(f.cyclomatic_complexity)
        grades.append(g)

    grade_counts = {}
    for g in grades:
        grade_counts[g] = grade_counts.get(g, 0) + 1

    grade_str = " ".join(f"{g}:{grade_counts.get(g,0)}" for g in "ABCDF" if g in grade_counts)

    return f"""## {_t('一、结构概览', lang)}

| {_t('维度', lang)} | {_t('说明', lang)} | {_t('说明', lang)} |
|------|------|------|
| {_t('总行数', lang)} | {structure.total_lines}行 | {_t('包含空行', lang)} |
| {_t('有效代码行(SLOC)', lang)} | {structure.sloc}行 | {_t('有效语句', lang)} |
| {_t('类数量', lang)} | {structure.class_count}个 | |
| {_t('函数数量', lang)} | {structure.function_count}个 | {_t('模块级', lang)} |
| {_t('方法数量', lang)} | {structure.method_count}个 | {_t('含继承方法', lang)} |
| {_t('导入数量', lang)} | {structure.import_count}个 | |
| {_t('参数总数', lang)} | {structure.total_arguments}个 | |

**{_t('复杂度分布', lang)}**: {grade_str}"""


def _section_2(structure, lang="en") -> str:
    """二、架构分析"""
    lines = [f"## {_t('二、架构分析', lang)}\n"]

    if structure.classes:
        lines.append(f"### {_t('类结构', lang)}\n")
        for cls in structure.classes:
            bases = ", ".join(cls.bases) if cls.bases else _t("无", lang)
            methods = ", ".join(m.name for m in cls.methods[:10])
            if cls.method_count > 10:
                methods += f" ... ({_t('共', lang)}{cls.method_count}个)"
            lines.append(f"**{cls.name}** ({_t('继承', lang)}: {bases})")
            lines.append(f"- {_t('方法', lang)}: {methods}")
            lines.append("")

    # 设计模式推断
    lines.append(f"### {_t('设计模式推断', lang)}\n")
    patterns = []
    for cls in structure.classes:
        method_names = [m.name for m in cls.methods]
        if '__init__' in method_names and len(cls.bases) == 0:
            patterns.append(f"- {cls.name}: {_t('基础类', lang)}")
        elif any(m.is_classmethod for m in cls.methods):
            patterns.append(f"- {cls.name}: {_t('含类方法（可能的工厂/注册模式）', lang)}")
        elif any(m.is_staticmethod for m in cls.methods):
            patterns.append(f"- {cls.name}: {_t('含静态方法（工具类）', lang)}")

    if patterns:
        lines.extend(patterns)
    else:
        lines.append(f"- {_t('未检测到明显的设计模式', lang)}")

    return "\n".join(lines)


def _section_3(structure, lang="en") -> str:
    """三、复杂度分析"""
    lines = [f"## {_t('三、复杂度分析', lang)}\n"]
    lines.append(f"| {_t('类/方法', lang)} | {_t('位置', lang)} | {_t('圈复杂度', lang)} | {_t('认知复杂度', lang)} | {_t('行数', lang)} | {_t('评级', lang)} |")
    lines.append("|---------|------|:---:|:---:|:---:|:---:|")

    for f in structure.all_functions:
        grade = _complexity_grade(f.cyclomatic_complexity)
        icon = _grade_color(grade)
        loc = f"L{f.lineno}" if f.lineno else "?"
        qn = f.qualified_name
        lines.append(
            f"| {qn} | {loc} | {f.cyclomatic_complexity} | "
            f"{f.cognitive_complexity} | {f.line_count} | {icon}{grade} |"
        )

    # 整体评级
    ccs = [f.cyclomatic_complexity for f in structure.all_functions]
    if ccs:
        avg_cc = sum(ccs) / len(ccs)
        max_cc = max(ccs)
        grade_counts = {}
        for cc in ccs:
            g = _complexity_grade(cc)
            grade_counts[g] = grade_counts.get(g, 0) + 1
        dominant = max(grade_counts, key=grade_counts.get)
        lines.append(f"\n**{_t('整体评级', lang)}**: {dominant}级 "
                      f"({grade_counts.get(dominant,0)}个, "
                      f"{grade_counts.get(dominant,0)/len(ccs)*100:.0f}%) "
                      f"| {_t('平均', lang)}: {avg_cc:.1f} | {_t('最大', lang)}: {max_cc}")

    return "\n".join(lines)


def _section_4(call_graph, lang="en") -> str:
    """四、调用图分析"""
    lines = [f"## {_t('四、调用图分析', lang)}\n"]

    lines.append(f"**{_t('调用边', lang)}**: {len(call_graph.edges)}条  ")
    lines.append(f"**{_t('用户定义函数', lang)}**: {len(call_graph.user_functions)}个  ")
    lines.append(f"**{_t('被调用函数', lang)}**: {len(call_graph.called_functions)}个  ")
    lines.append(f"**{_t('最大调用深度', lang)}**: {call_graph.max_depth}\n")

    # 调用关系表
    if call_graph.edges:
        lines.append(f"### {_t('调用关系', lang)}\n")
        lines.append(f"| {_t('调用者', lang)} | {_t('被调用者', lang)} | {_t('行号', lang)} |")
        lines.append("|--------|----------|------|")
        for e in call_graph.edges[:30]:  # 限制显示数量
            lines.append(f"| {e.caller} | {e.callee} | L{e.lineno} |")
        if len(call_graph.edges) > 30:
            lines.append(f"\n*（{_t('仅显示前', lang)}30{_t('共', lang)}{len(call_graph.edges)}条）*")

    # 入口点
    if call_graph.entry_points:
        lines.append(f"\n### {_t('入口点', lang)}\n")
        for ep in call_graph.entry_points:
            lines.append(f"- `{ep}`")

    return "\n".join(lines)


def _section_5(impact_analysis, lang="en") -> str:
    """五、影响面分析"""
    lines = [f"## {_t('五、影响面分析', lang)}\n"]

    if impact_analysis.impacts:
        lines.append(f"| {_t('修改目标', lang)} | {_t('直接影响', lang)} | {_t('间接影响', lang)} | {_t('总影响', lang)} |")
        lines.append("|----------|:--------:|:--------:|:------:|")
        for imp in impact_analysis.impacts[:20]:
            lines.append(
                f"| {imp.function} | {len(imp.direct_impact)} | "
                f"{len(imp.indirect_impact)} | **{imp.total_impact}** |"
            )
    else:
        lines.append(_t("无调用关系，影响面分析不适用", lang) + "。")

    return "\n".join(lines)


def _section_6(dead_code_result, lang="en") -> str:
    """六、死代码检测"""
    lines = [f"## {_t('六、死代码检测', lang)}\n"]

    lines.append(f"**{_t('覆盖率', lang)}**: {dead_code_result.coverage}% "
                  f"({dead_code_result.total_user_functions - len(dead_code_result.unreachable)}"
                  f"/{dead_code_result.total_user_functions})\n")

    if dead_code_result.unreachable:
        lines.append(f"### {_t('未覆盖函数', lang)}\n")
        lines.append(f"| {_t('函数', lang)} | {_t('风险', lang)} |")
        lines.append("|------|------|")
        for func in dead_code_result.unreachable:
            lines.append(f"| `{func}` | ⚠️ {_t('无调用路径', lang)} |")
    else:
        lines.append(f"✅ {_t('所有用户定义函数均有调用路径', lang)}。")

    if dead_code_result.special_excluded:
        lines.append(f"\n*（排除{len(dead_code_result.special_excluded)}{_t('特殊方法', lang)}）*")

    return "\n".join(lines)


def _section_7(dependency_result, lang="en") -> str:
    """七、依赖分析"""
    lines = [f"## {_t('七、依赖分析', lang)}\n"]

    lines.append(f"**{_t('循环导入', lang)}**: {'❌ 有' if dependency_result.has_circular else '✅ ' + _t('无', lang)}\n")

    lines.append(f"| {_t('依赖类型', lang)} | {_t('数量', lang)} | {_t('模块列表', lang)} |")
    lines.append("|----------|:----:|----------|")
    lines.append(f"| {_t('stdlib', lang)} | {len(dependency_result.standard_lib)} | "
                  f"{', '.join(dependency_result.standard_lib[:10])}{'...' if len(dependency_result.standard_lib) > 10 else ''} |")
    lines.append(f"| {_t('third-party', lang)} | {len(dependency_result.third_party)} | "
                  f"{', '.join(dependency_result.third_party[:10])}{'...' if len(dependency_result.third_party) > 10 else ''} |")
    lines.append(f"| {_t('local', lang)} | {len(dependency_result.local)} | "
                  f"{', '.join(dependency_result.local[:10])}{'...' if len(dependency_result.local) > 10 else ''} |")

    if dependency_result.circular_cycles:
        lines.append(f"\n### {_t('循环依赖详情', lang)}\n")
        for cycle in dependency_result.circular_cycles:
            lines.append(f"- {' → '.join(cycle)}")

    return "\n".join(lines)


def _section_8(ai_analysis, lang="en") -> str:
    """八、代码意图（Agent层）"""
    lines = [f"## {_t('八、代码意图', lang)}\n"]

    if ai_analysis:
        for key, value in ai_analysis.items():
            lines.append(f"### {key}\n")
            lines.append(str(value))
            lines.append("")
    else:
        lines.append(f"*{_t('此部分由Agent层(LLM)分析生成', lang)}*")
        lines.append(f"*{_t('code_analyzer工具仅提供静态数据', lang)}*")

    return "\n".join(lines)


def _section_9(structure, lang="en") -> str:
    """九、文档覆盖率"""
    lines = [f"## {_t('九、文档覆盖率', lang)}\n"]

    total = len(structure.all_functions)
    documented = sum(1 for f in structure.all_functions if f.docstring and f.docstring_length > 10)
    coverage = (documented / total * 100) if total > 0 else 100

    lines.append(f"| {_t('指标', lang)} | {_t('数值', lang)} |")
    lines.append(f"|------|------|")
    lines.append(f"| {_t('总函数/方法', lang)} | {total} |")
    lines.append(f"| {_t('有docstring', lang)} | {documented} |")
    lines.append(f"| **{_t('覆盖率', lang)}** | **{coverage:.1f}%** |")

    # 缺失docstring的方法
    missing = [f for f in structure.all_functions if not f.docstring or f.docstring_length <= 10]
    if missing:
        lines.append(f"\n### {_t('缺失docstring的方法', lang)}\n")
        lines.append(f"| {_t('函数', lang)} | {_t('位置', lang)} | {_t('优先级', lang)} |")
        lines.append(f"|------|------|--------|")
        for f in missing[:15]:
            grade = _complexity_grade(f.cyclomatic_complexity)
            priority = "P0" if grade in ("D", "F") else "P1" if grade == "C" else "P2"
            lines.append(f"| `{f.qualified_name}` | L{f.lineno} | {priority} |")
        if len(missing) > 15:
            lines.append(f"\n*（{_t('仅显示前', lang)}15{_t('共', lang)}{len(missing)}个缺失）*")

    return "\n".join(lines)


def _section_10(structure, call_graph, dead_code, dependency, lang="en") -> str:
    """十、重构建议"""
    lines = [f"## {_t('十、重构建议', lang)}\n"]

    suggestions_p0 = []
    suggestions_p1 = []

    # P0: 高复杂度函数
    for f in structure.all_functions:
        if f.cyclomatic_complexity > 20:
            suggestions_p0.append(
                f"{_t('函数', lang)} `{f.qualified_name}` {_t('圈复杂度', lang)}{f.cyclomatic_complexity}(D级)，{_t('建议拆分', lang)}"
            )
        elif f.cyclomatic_complexity > 10:
            suggestions_p1.append(
                f"{_t('函数', lang)} `{f.qualified_name}` {_t('圈复杂度', lang)}{f.cyclomatic_complexity}(C级)，{_t('可考虑简化', lang)}"
            )

    # P0: 死代码
    for func in dead_code.unreachable:
        suggestions_p1.append(f"{_t('函数', lang)} `{func}` {_t('无调用路径，可考虑移除或添加入口', lang)}")

    # P1: 循环依赖
    if dependency.has_circular:
        for cycle in dependency.circular_cycles:
            suggestions_p0.append(f"{_t('循环导入', lang)}: {' → '.join(cycle)}，{_t('需重构依赖方向', lang)}")

    # P1: 无docstring的复杂函数
    for f in structure.all_functions:
        if (not f.docstring or f.docstring_length <= 10) and f.cyclomatic_complexity > 5:
            suggestions_p1.append(
                f"{_t('函数', lang)} `{f.qualified_name}` {_t('复杂度', lang)}{f.cyclomatic_complexity}{_t('复杂度但无docstring', lang)}"
            )

    if suggestions_p0:
        lines.append(f"### P0级（{_t('建议立即修复', lang)}）\n")
        lines.append(f"| # | {_t('建议', lang)} |")
        lines.append("|---|------|")
        for i, s in enumerate(suggestions_p0, 1):
            lines.append(f"| {i} | {s} |")

    if suggestions_p1:
        lines.append(f"\n### P1级（{_t('建议后续优化', lang)}）\n")
        lines.append(f"| # | {_t('建议', lang)} |")
        lines.append("|---|------|")
        for i, s in enumerate(suggestions_p1[:10], 1):
            lines.append(f"| {i} | {s} |")

    if not suggestions_p0 and not suggestions_p1:
        lines.append(f"✅ {_t('未发现需要重构的问题', lang)}。")

    return "\n".join(lines)


def _section_11(structure, call_graph, dead_code, dependency, lang="en") -> str:
    """十一、综合评估"""
    lines = [f"## {_t('十一、综合评估', lang)}\n"]

    # 各维度评分 (0-10)
    # 复杂度: 平均CC越低越好
    avg_cc = structure.avg_complexity
    complexity_score = max(0, min(10, 10 - avg_cc))

    # 文档: 覆盖率越高越好
    doc_score = structure.doc_coverage / 10

    # 结构: 函数数量合理+类结构清晰
    struct_score = 7.0  # 基础分
    if structure.class_count > 0 and structure.method_count > 0:
        struct_score += 1  # 有类结构
    if structure.function_count + structure.method_count < 50:
        struct_score += 1  # 规模合理
    struct_score = min(10, struct_score)

    # 死代码: 覆盖率越高越好
    dead_score = dead_code.coverage / 10

    # 依赖: 无循环+合理分类
    dep_score = 8.0
    if dependency.has_circular:
        dep_score -= 3
    if len(dependency.third_party) > 10:
        dep_score -= 1
    dep_score = max(0, dep_score)

    # 综合分
    weights = {"complexity": 0.25, "doc": 0.25, "structure": 0.2,
               "dead_code": 0.15, "dependency": 0.15}
    total = (
        complexity_score * weights["complexity"]
        + doc_score * weights["doc"]
        + struct_score * weights["structure"]
        + dead_score * weights["dead_code"]
        + dep_score * weights["dependency"]
    )

    grade = "A" if total >= 8.5 else "B" if total >= 7 else "C" if total >= 5.5 else "D" if total >= 4 else "F"

    lines.append(f"| {_t('维度', lang)} | {_t('得分', lang)} | {_t('权重', lang)} | {_t('说明', lang)} |")
    lines.append("|------|:----:|:----:|------|")
    lines.append(f"| {_t('复杂度', lang)} | {complexity_score:.1f} | 25% | {_t('平均', lang)}CC={avg_cc:.1f} |")
    lines.append(f"| {_t('文档', lang)} | {doc_score:.1f} | 25% | {_t('覆盖率', lang)}={structure.doc_coverage:.1f}% |")
    lines.append(f"| {_t('结构', lang)} | {struct_score:.1f} | 20% | {_t('类数量', lang)}{structure.class_count}个+{_t('函数数量', lang)}{structure.function_count}个 |")
    lines.append(f"| {_t('死代码', lang)} | {dead_score:.1f} | 15% | {_t('覆盖率', lang)}={dead_code.coverage:.1f}% |")
    lines.append(f"| {_t('依赖', lang)} | {dep_score:.1f} | 15% | {_t('循环导入', lang)}={dependency.has_circular} |")
    lines.append(f"| **{_t('综合', lang)}** | **{total:.1f}** | **100%** | **{grade}级** |")

    return "\n".join(lines)


def _section_12(structure, call_graph, dead_code, lang="en") -> str:
    """十二、总结"""
    lines = [f"## {_t('十二、总结', lang)}\n"]

    # 优势
    strengths = []
    if structure.avg_complexity <= 5:
        strengths.append("整体复杂度低，代码可读性好" if lang == "zh" else "Low overall complexity, good code readability")
    if structure.doc_coverage >= 80:
        strengths.append("文档覆盖率高" if lang == "zh" else "High documentation coverage")
    if not dead_code.unreachable:
        strengths.append("无死代码，所有函数均有调用路径" if lang == "zh" else "No dead code, all functions have call paths")
    if call_graph.max_depth <= 3:
        strengths.append("调用层次浅，结构清晰" if lang == "zh" else "Shallow call depth, clear structure")

    # 问题
    issues = []
    high_cc = [f for f in structure.all_functions if f.cyclomatic_complexity > 10]
    if high_cc:
        issues.append(f"{len(high_cc)}个函数复杂度>10，需关注" if lang == "zh" else f"{len(high_cc)} functions with complexity>10, needs attention")
    if dead_code.unreachable:
        issues.append(f"{len(dead_code.unreachable)}个函数无调用路径" if lang == "zh" else f"{len(dead_code.unreachable)} functions with no call path")
    if structure.doc_coverage < 50:
        issues.append("文档覆盖率不足50%" if lang == "zh" else "Documentation coverage below 50%")

    lines.append(f"| {_t('优势', lang)} | {_t('问题', lang)} |")
    lines.append("|------|------|")

    max_rows = max(len(strengths), len(issues))
    for i in range(max_rows):
        s = f"✅ {strengths[i]}" if i < len(strengths) else ""
        issue = f"⚠️ {issues[i]}" if i < len(issues) else ""
        lines.append(f"| {s} | {issue} |")

    if not strengths and not issues:
        lines.append(f"| ✅ {_t('无明显问题', lang)} | ⚠️ {_t('无明显优势', lang)} |")

    # 整体评价
    total_funcs = len(structure.all_functions)
    total_lines = structure.total_lines
    lines.append(f"\n**{_t('整体评价', lang)}**: {total_lines}行代码，{structure.class_count}个类，"
                  f"{total_funcs}个函数/方法，{_t('复杂度', lang)}{_t('平均', lang)}{structure.avg_complexity:.1f}")

    return "\n".join(lines)
